# Generated by Django 3.1.6 on 2021-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
