# Generated by Django 3.1.6 on 2021-02-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitation_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_used',
        ),
    ]
