# Generated by Django 3.1.6 on 2021-03-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20210302_1332'),
        ('users', '0004_remove_invitation_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='flashcard',
        ),
        migrations.AddField(
            model_name='ownership',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flashcards.collection'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owned_flashcards',
            field=models.ManyToManyField(through='users.Ownership', to='flashcards.Collection'),
        ),
    ]
