# Generated by Django 3.1.6 on 2021-03-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210302_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owned_flashcards',
            new_name='owned_collections',
        ),
    ]
