# Generated by Django 3.1.6 on 2021-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20210302_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='collection_thumbnails'),
        ),
    ]
