# Generated by Django 3.1.6 on 2021-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20210302_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
