# Generated by Django 3.1.6 on 2021-03-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20210305_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
